export enum TipoDocumento {
  RG_ALUNO = 'RG_ALUNO',
  CPF_ALUNO = 'CPF_ALUNO',
  CERTIDAO_NASCIMENTO = 'CERTIDAO_NASCIMENTO',
  COMPROVANTE_RESIDENCIA_ALUNO = 'COMPROVANTE_RESIDENCIA_ALUNO',
  FOTO_3X4 = 'FOTO_3X4',
  HISTORICO_ESCOLAR = 'HISTORICO_ESCOLAR',

  RG_RESPONSAVEL = 'RG_RESPONSAVEL',
  CPF_RESPONSAVEL = 'CPF_RESPONSAVEL',
  COMPROVANTE_RESIDENCIA_RESP = 'COMPROVANTE_RESIDENCIA_RESP',
}
